# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu16.04"
  config.ssh.insert_key = false

  #http
  config.vm.network "forwarded_port", guest: 80, host: 8070
  config.vm.network "forwarded_port", guest: 443, host: 8443

  #メール用
  config.vm.network "forwarded_port", guest: 15, host: 8015
  

  #ssh用
  config.vm.network "forwarded_port", guest: 22, host: 2201, id: "ssh"

  #予備Oracle用
  config.vm.network "forwarded_port", guest: 1555, host: 1555

  #server用 docker-compose.ymlのserverでhostはこの値にする。デフォルト5000だとポートが使えない為
  config.vm.network "forwarded_port", guest: 8060, host: 8060
  #http
  config.vm.network "forwarded_port", guest: 8050, host: 8050
  
  config.vm.synced_folder "./data", "/vagrant", type: "virtualbox"
#  config.vm.provider "virtualbox" do |vb|
#    vb.gui = false
#    vb.memory = "5120"
#  end
  config.vm.provision "shell" ,path: './provision_root.sh'
#  config.vm.provision "shell" ,path: './provision_resouse.sh'
#  config.vm.provision "file" , source: "./vimrc", destination: "./"

  #毎回実行
#  config.vm.provision "shell", run: "always" ,path: './provision_redash-run.sh'
end
